[build]
  functions = "pagamentos/netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

# Redirects para as functions
[[redirects]]
  from = "/api/mbway/payment"
  to = "/.netlify/functions/mbway-payment"
  status = 200

# Redirects para a página de pagamento
[[redirects]]
  from = "/pagamento"
  to = "/pagamentos/"
  status = 200

[[redirects]]
  from = "/pagamento/*"
  to = "/pagamentos/"
  status = 200

[[redirects]]
  from = "/pay"
  to = "/pagamentos/"
  status = 200

# Forçar HTTPS para o domínio personalizado
[[redirects]]
  from = "http://pagamentos.bewaterlisboa.pt/*"
  to = "https://pagamentos.bewaterlisboa.pt/:splat"
  status = 301
  force = true

# Exceções para functions do pagamentos subdomain - deve vir ANTES do catch-all
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = {Domain = ["pagamentos.bewaterlisboa.pt"]}

# Redirect para raiz do pagamentos no subdomain
[[redirects]]
  from = "/"
  to = "/pagamentos/"
  status = 200
  conditions = {Domain = ["pagamentos.bewaterlisboa.pt"]}

# Redirect para domínio personalizado pagamentos.bewaterlisboa.pt (catch-all)
[[redirects]]
  from = "/*"
  to = "/pagamentos/:splat"
  status = 200
  conditions = {Domain = ["pagamentos.bewaterlisboa.pt"]} 